### ISSUE TITLE
Invoice field on Project Creation Step

### ISSUE THREAD

**Issue by PrateekNarang** [ColoredCow/employee-portal#47]
Email for invoice should ALSO be part of Client creation step. And at the project creation, I should have the ability to edit that.

Also, I should be able to add more than one email, and name for this.

**Comment by rathorevaibhav** [comment]
1. I think since we're capturing the client email, we can use that in case invoice email for that client's project is missing. There should be a way to notify if any communication that is supposed to be done with project invoice email is being done instead with the client email.

2. I agree. A client can have multiple emails. There should be an ability to add multiple name/email pairs. Just thinking if a project's invoice email can be multiple or does sending invoices to multiple emails make sense?

**Comment by rathorevaibhav** [comment]
Emails for invoices in a project are being tracked in #173 

Closing this one.
