### ISSUE TITLE
Visiblity of communication with Candidate

### ISSUE THREAD

**Issue by PrateekNarang** [ColoredCow/employee-portal#63]
1. What we have communicated with the candidate so far should be visible.
2. What we are going to communicate with the candidate should also be visible.

I want to reject a candidate but don't know what she is going to receive.

**Comment by rathorevaibhav** [comment]
@PrateekNarang I suppose this functionality is dependent on #70. Once the emails functionality is done, this can be taken forward with emails from the system. Since that is scheduled for Apr 7th, I am targeting to finish this on Apr 8th. In the meantime, I am targeting to set up the database and the workflow for the communication content.

Also, need some clarification on the following:

**What we have communicated with the candidate so far should be visible**
We can show a button to send email to an applicant in each round, once an action (accept/reject) for that round is taken. This button will open up a modal with a field to add/modify mail content. There'll be a send mail button to trigger the mail and save the communication in the database.
Once sent, we can hide the button (so that the mail doesn't go again), and a small link to see what went into the email. 

**What we are going to communicate with the candidate should also be visible**
Didn't completely understand the requirements here. Does it mean some content can be pre-populated in the mail content depending on the action for that round?
